---
- name: Install packeges
  ansible.builtin.package:
    name: apache2
    state: present

- name: Template html index-page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '644'
  notify: restart_apache

- name: Add line
  ansible.builtin.shell: echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore && echo 1 > /proc/sys/net/ipv4/conf/lo/arp_ignore && echo 2 > /proc/sys/net/ipv4/conf/all/arp_announce && echo 2 > /proc/sys/net/ipv4/conf/lo/arp_announce

- name: Check loopback ip
  ansible.builtin.command: "ip -4 -br a show dev lo"
  register: ip_check

- name: RS loopback settings
  ansible.builtin.shell: ip a a {{ loopback_first_ip }}/{{ loopback_first_port }} dev lo && ip a a {{ loopback_second_ip }}/{{ loopback_second_port }} dev lo
  when: "(loopback_first_ip | string) and (loopback_second_ip | string) not in ip_check.stdout"


