---
- name: Install packeges
  ansible.builtin.package:
    name: apache2
    state: present

- name: Template html index-page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '644'
  notify: restart_apache

- name: Add line
  ansible.builtin.shell: echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore && echo 1 > /proc/sys/net/ipv4/conf/lo/arp_ignore && echo 2 > /proc/sys/net/ipv4/conf/all/arp_announce && echo 2 > /proc/sys/net/ipv4/conf/lo/arp_announce

#- name: Add line arp_ignore
#  ansible.builtin.lineinfile:
#    dest: '{{ item }}'
#    line: 1
#  with_items: 
#    - "/proc/sys/net/ipv4/conf/all/arp_ignore"
#    - "/proc/sys/net/ipv4/conf/lo/arp_ignore"
#  become: true
#  
#- name: Add line arp_anounce
#  ansible.builtin.lineinfile:
#    dest: '{{ item }}'
#    line: 2
#  with_items: 
#    - "/proc/sys/net/ipv4/conf/all/arp_announce"
#    - "/proc/sys/net/ipv4/conf/lo/arp_announce"
  

- name: RS loopback settings
  ansible.builtin.shell: ip a a 192.168.56.33/32 dev lo && ip a a 192.168.56.34/32 dev lo
  tags: add_loopback
